# Generated by Django 6.0.5 on 2026-05-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='bill_no',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
