# Generated by Django 6.0.5 on 2026-05-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_remove_sale_bill_no_remove_sale_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='bill_no',
            field=models.CharField(default='TEMP', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
