# Generated by Django 6.0.5 on 2026-05-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_sale_bill_no_alter_sale_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='bill_no',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
