# Generated by Django 6.0.5 on 2026-05-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_sale_bill_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
