# Generated by Django 6.0.5 on 2026-05-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_production_created_at_production_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='payment_term',
        ),
        migrations.AddField(
            model_name='sale',
            name='collected_payment',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='due',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='sales_person_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
