# Generated by Django 6.0.5 on 2026-05-25 17:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_remove_sale_payment_term_sale_collected_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales_person_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
