# Generated by Django 5.2.6 on 2026-05-26 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_rawmaterial_created_at_sale_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('rd_name', models.CharField(max_length=100)),
                ('retail_partner', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('customer_name', models.CharField(default='', max_length=200)),
                ('sales_person_name', models.CharField(default='', max_length=200)),
                ('address', models.TextField()),
                ('collected_payment', models.FloatField(default=0)),
                ('due', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_count', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.salebill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
