# Generated by Django 5.2.6 on 2026-05-26 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_salebill_saleitem_delete_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('rd_name', models.CharField(max_length=100)),
                ('retail_partner', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('customer_name', models.CharField(default='', max_length=200)),
                ('sales_person_name', models.CharField(default='', max_length=200)),
                ('address', models.TextField()),
                ('collected_payment', models.FloatField(default=0)),
                ('due', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='total_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.bill'),
        ),
        migrations.DeleteModel(
            name='SaleBill',
        ),
    ]
